snapcraft.yaml: select a generic TERM value
Due to the sheer number of possible terminal emulators a user could be
using, we have two choices:
1) install the terminfo packages for all possible terminal emulators, or
2) set the TERM variable to a well-supported emulator

xterm is a solid default for most any conformant terminal emulator, and
will allow our snap to be smaller by avoiding staging terminfo packages.

Resolves this runtime error:

dilyn@Ares:~/git/gotop -> gotop
2024/06/25 00:53:12 gopsutil reports Number of warnings: 1
2024/06/25 00:53:12 gopsutil reports Number of warnings: 1
9| errors encountered; from /home/dilyn/snap/gotop/x1/.cache/gotop/errors.log:
00:53:12 remote.go:74: Remote: no remote URL provided; disabling extension
00:53:12 temp_nix.go:35: error opening smart info for nvme0n1: unknown drive type
00:53:12 temp_nix.go:35: error opening smart info for nvme1n1: unknown drive type
00:53:12 temp_nix.go:35: error opening smart info for nvme2n1: unknown drive type
00:53:12 temp_nix.go:35: error opening smart info for sda: unknown drive type
00:53:12 temp_nix.go:35: error opening smart info for sdb: unknown drive type
termbox: error while reading terminfo data: termbox: unsupported terminal

Some information on the environment section for apps can be found here:
https://snapcraft.io/docs/snapcraft-yaml-reference

Signed-off-by: Dilyn Corner <dilyn.corner@canonical.com>